### ISSUE TITLE
[Bug]: Warning when using with svelte version ^4.0.0

### ISSUE THREAD

**Issue by netcodedev** [SauravKanchan/svelte-chartjs#116] opened 2023-07-24 13:23 UTC
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Library should just work without errors or warnings

### Reproduction

https://codesandbox.io/p/sandbox/black-wood-2hz8vj

### chart.js version

^4.3.0

### svelte-chartjs version

^3.1.2

### Possible solution

Update the dependency to svelte@^4.0.0

**Comment by okuruu** [comment] 2023-07-24 14:55
I have the same issue..

**Comment by diramazioni** [comment] 2023-08-06 18:05
More then a warning, it just doesn't work!, And doesn't produce any visible error either, beside the console log hinting to add import for Filler option that I did I see no further error.
In ts/vscode I see error if I hover in `{data}`  for` <Line {data} options={{ responsive: true }} />`
```
Type '{ labels: string[]; datasets: { label: string; fill: boolean; lineTension: number; backgroundColor: string; borderColor: string; borderCapStyle: string; borderDash: never[]; borderDashOffset: number; ... 10 more ...; data: number[]; }[]; }' is not assignable to type 'ChartData<"line", (number | Point)[], unknown>'.
  Types of property 'datasets' are incompatible.
    Type '{ label: string; fill: boolean; lineTension: number; backgroundColor: string; borderColor: string; borderCapStyle: string; borderDash: never[]; borderDashOffset: number; borderJoinStyle: string; ... 9 more ...; data: number[]; }[]' is not assignable to type 'ChartDataset<"line", (number | Point)[]>[]'.
      Type '{ label: string; fill: boolean; lineTension: number; backgroundColor: string; borderColor: string; borderCapStyle: string; borderDash: never[]; borderDashOffset: number; borderJoinStyle: string; ... 9 more ...; data: number[]; }' is not assignable to type 'ChartDataset<"line", (number | Point)[]>'.
```
so the problem may be due to a change of chartjs dataset format?

**Comment by Renkas** [comment] 2023-08-08 20:47
so this library is blocking me from using svelte4 in my project. Will this be resolved anytime soon?

**Comment by SkepticMystic** [comment] 2023-08-17 06:31
I can confirm that @rbozan's suggestion (#112) works in my project:
> For installing through npm:
> 
> ```
> npm i github:SauravKanchan/svelte-chartjs#renovate/svelte-4.x --force
> ```
> 
> Or you can just override it in package.json
> 
> ```json
>   "overrides": {
>     "svelte-chartjs": {
>       "svelte": ">=4.x"
>     }
>   }
> ```

Specifically, the `overrides` option works for me, I have not tried the first approach.

**Comment by thomasdom** [comment] 2023-09-05 15:50
@SauravKanchan any updates on this topic? We'll be implementing the workaround mentioned [above](https://github.com/SauravKanchan/svelte-chartjs/issues/116#issuecomment-1681693028), but it would be better if the lib was updated properly 👍🏼

**Comment by exislow** [comment] 2023-10-17 09:18
+1 

Can you please update it?

**Comment by niemyjski** [comment] 2024-01-30 14:19
I think this will be resolved in the next update.

**Comment by niemyjski** [comment] 2024-01-30 23:38
This is fixed in the latest release https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v3.1.4

**Closed by niemyjski** 2024-01-30 23:38 UTC
Labels: bug
